### ISSUE TITLE
landfire raster extent

### ISSUE THREAD

**Issue by Senkichi** [PLJV/BrotherOrange#1]
@ktaylora  can you take a look at reading in the landfire raster? when I read it in the extent is wrong, and I'm not sure how to fix it other than manually assigning the extent. That's a functional workaround, but i'd really like to understand why its not working in the first place. I'll load in the code i have to the bottom of the ebird file with notes now

**Comment by ktaylora** [comment]
Sure. I'll see if I can re-produce the problem and fix it. It might be a question of just appending the proper projection when the raster is read-in. I think it's ok to leave this static or fixed at runtime; landfire projections aren't changing anytime soon.

**Comment by ktaylora** [comment]
Ran into some issues. Changes to landfire "getter" first : Did a refactor to get it running and pretty-up the code. I renamed the function to lowercase with underscores and removed the old CamelCase convention that's not used for R, dropped un-needed getwd() calls (R assumes you are working in the CWD by default), references to the climate_data exdir were changes to landfire_data, added lapply comprehension to the unpack operation on landfire_list, made the return a call to an anonymous function (no need to store in a local variable), dropped the unused 'year' parameter.

**Comment by ktaylora** [comment]
The CRS of the EVH/EVC rasters is undefined. I added some code that will automatically look for a metadata shapefile shipped with landfire and bogart the CRS from this file and assign it to the rasters. Let me know if this fixes your problem.

**Comment by Senkichi** [comment]
Nah, the issue remains the same. After running the refactored code which searches for the existing CRS from the landifre folders the extent of the landfire data is

xmin        : 0 
xmax        : 77104 
ymin        : 0 
ymax        : 48642 

and the extent of the worldclim data in the same CRS is 

class       : Extent 
xmin        : -111.0583 
xmax        : -93.50833 
ymin        : 25.83333 
ymax        : 49 

While the extents shouldnt be the same, since at this point the worldclim data is bounded and the landfire data is not, the worldclim extent should be within the landfire extent and right now its wholly outside. I think part of it has to do with a mismatch of units, I dont think the raster is in the same projection as the shapefile that we're using in the function to get the crs. But even when I assigned what I thought was the correct landfire crs (+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m no_defs per https://www.landfire.gov/faq.php?faq_id=274&sort_id=1) the extents still don't translate.

**Comment by ktaylora** [comment]
Something is odd about the projection shown above for Landfire. The bounding box you are showing is in meters, but Landfire is WGS84 and should be in decimal degrees (like worldclim). I can verify this from pulling the extent from the changes I pushed up yesterday.

**Comment by Senkichi** [comment]
Yeah, I don't get it. Their FAQ says its in Albers, but even when you set the CRS to Albers as specified by their FAQ and project another object to the CRS in their FAQ the two don't match. As an example

> extent(landfire)
class       : Extent 
xmin        : 0 
xmax        : 77104 
ymin        : 0 
ymax        : 48642 
> extent(flyway)
class       : Extent 
xmin        : -1206164 
xmax        : 237149.9 
ymin        : 310896.2 
ymax        : 2959098

**Comment by ktaylora** [comment]
Ah, shit. I hate that projection. It's the one Alex is always using. It's not an internationally recognized CRS. It doesn't even have a standard EPSG. We'll have to pull it from the web and assign it explicitly in R. Here's a full write-up with the .prj file : http://spatialreference.org/ref/sr-org/7301/

**Comment by Senkichi** [comment]
Nah, I ran the landfire getter fresh this morning with your altered code from yesterday. Was it working fine on yours? The main reason I was hesitant to reproject the full raster to worldclim projections was that it takes effing forever, and I was hoping to crop the landfire to a central flyway bounding area that was projected to the landfire projection. But I'll clear temp files and run your code now.

**Comment by Senkichi** [comment]
Ahhhhhhhh. Fun.

**Comment by ktaylora** [comment]
Let me do some tinkering with the getter this morning. I think I can get it working.

**Comment by ktaylora** [comment]
Ok, That was fairly easy. I just dropped the .ovr filename extension from the landfire filenames and raster::stack then read the proper projection information. See: 

```
>     all_files <-
+         raster::stack(gsub(list.files(
+             "landfire_data",
+             pattern = "ovr$",
+             recursive = T,
+             full.names = T
+           ),
+           pattern = "[.]...",
+           replacement = ""
+         ))
> all_files
class       : RasterStack 
dimensions  : 97283, 154208, 15001816864, 2  (nrow, ncol, ncell, nlayers)
resolution  : 30, 30  (x, y)
extent      : -2362425, 2263815, 258945, 3177435  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
names       : us_140evc, us_140evh 
min values  :     -9999,     -9999 
max values  :       129,       112 

```

**Comment by Senkichi** [comment]
Nice! I guess by specifying the file it was preventing stack from grabbing the metadata. Thanks for the prompt help, that has been my bane for several days now.

**Comment by ktaylora** [comment]
NP. I also added an if-statement to the code that will check for existing landfire zipfiles before downloading EVC/EVH data. I noticed it took forever to fetch on my machine... which is silly if it's already sitting there. Will warn the user if it used an existing zip.
